// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `fingerprint_path`

Future<List<AudioFingerprint>> getBatchFingerprints({
  required List<String> paths,
}) => RustLib.instance.api.crateFingerprintGetBatchFingerprints(paths: paths);

class AudioFingerprint {
  final String path;
  final String fingerprint;
  final double durationSecs;

  const AudioFingerprint({
    required this.path,
    required this.fingerprint,
    required this.durationSecs,
  });

  @override
  int get hashCode =>
      path.hashCode ^ fingerprint.hashCode ^ durationSecs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFingerprint &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          fingerprint == other.fingerprint &&
          durationSecs == other.durationSecs;
}
