// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../pyin.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ms_to_samples`, `new`, `parse_pcm16le_bytes`, `parse_pcm16le_to_i16`, `process_pcm_bytes`

Future<void> initLogging() => RustLib.instance.api.cratePyinApiInitLogging();

Future<PyinProcessor> newProcessor({
  required int sampleRateHz,
  required int windowMs,
  required int hopMs,
}) => RustLib.instance.api.cratePyinApiNewProcessor(
  sampleRateHz: sampleRateHz,
  windowMs: windowMs,
  hopMs: hopMs,
);

Future<int> pushAndGetMidi({
  required PyinProcessor proc,
  required List<int> pcm16LeBytes,
}) => RustLib.instance.api.cratePyinApiPushAndGetMidi(
  proc: proc,
  pcm16LeBytes: pcm16LeBytes,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AudioAnalyzer>>
abstract class AudioAnalyzer implements RustOpaqueInterface {
  Stream<int> createStream();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AudioAnalyzer> newInstance({required PitchConfig config}) =>
      RustLib.instance.api.cratePyinApiAudioAnalyzerNew(config: config);

  Future<void> processChunk({required List<int> pcm16LeBytes});

  Future<Uint8List> processChunkCollect({required List<int> pcm16LeBytes});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PyinProcessor>>
abstract class PyinProcessor implements RustOpaqueInterface {}

class PitchConfig {
  final int sampleRateHz;
  final int updateIntervalMs;
  final int windowSizeMs;

  const PitchConfig({
    required this.sampleRateHz,
    required this.updateIntervalMs,
    required this.windowSizeMs,
  });

  @override
  int get hashCode =>
      sampleRateHz.hashCode ^ updateIntervalMs.hashCode ^ windowSizeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PitchConfig &&
          runtimeType == other.runtimeType &&
          sampleRateHz == other.sampleRateHz &&
          updateIntervalMs == other.updateIntervalMs &&
          windowSizeMs == other.windowSizeMs;
}
